export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ANSWER_ROUTE = '/answer'
export const ANSWER_CREATE = '/answer/create'
export const POLLS_CREATE = '/polls/create'
export const POLLS_ROUTE = '/polls'